# For use with ~/Scripts/tailscaleServe.sh
#   Format -> service_name:port

# Photos
#photos:2283 # moved to souei

# Tasks
tasks:3456

# Media
media:8096
sonarr:8989
rdt:6500
prowlarr:9696

# Music
music:4533
spotdl:8800
metube:8081

# AI
tavern:8000