# Run sudo systemctl restart tuned.service to udpate

[main]
summary=Optimize for headless Tiger Lake server stability while capping package power to 15W

[cpu]
governor=powersave
#energy_performance_preference=balance_power
energy_performance_preference=balance_performance 

[sysfs]
# Cap Long-Term Power Limit (PL1) in microwatts
#/sys/class/powercap/intel-rapl:0/constraint_0_power_limit_uw=15000000
/sys/class/powercap/intel-rapl:0/constraint_0_power_limit_uw=20000000

# Cap Short-Term Power Limit (PL2) in microwatts
#/sys/class/powercap/intel-rapl:0/constraint_1_power_limit_uw=18000000
/sys/class/powercap/intel-rapl:0/constraint_1_power_limit_uw=25000000
