# yaml-language-server: $schema=https://schemas.recyclarr.dev/v8/config-schema.json

sonarr:
  sonarr-anime-remux-1080p:
    base_url: http://sonarr:8989
    api_key: !secret sonarr_apikey

    quality_profiles:
      - trash_id: 20e0fc959f1f1704bed501f23bdae76f
        name: "[Anime] Watching - 1080p"
        reset_unmatched_scores:
          enabled: true
          except:
            - "Legacy x264 10bit"

      - trash_id: 20e0fc959f1f1704bed501f23bdae76f
        name: "[Anime] Planning - 1080p"
        reset_unmatched_scores:
          enabled: true
          except:
            - "Legacy x264 10bit"

    custom_formats:
      - trash_ids:
          - 4a20cfb76b5f92a8ca22b894b32e71be  # Multi-Episode
        assign_scores_to:
          - name: "[Anime] Planning - 1080p"
            score: -200
      - trash_ids:
          - 15a05bc7c1a36e2b57fd628f8977e2fc  # AV1
        assign_scores_to:
          - name: "[Anime] Watching - 1080p"
            score: 0
          - name: "[Anime] Planning - 1080p"
            score: 0

radarr:
  radarr-anime-remux-1080p:
    base_url: http://radarr:7878
    api_key: !secret radarr_apikey

    quality_profiles:
      - trash_id: 722b624f9af1e492284c4bc842153a38
        name: "[Anime] Watching - 1080p"
        reset_unmatched_scores:
          enabled: true
          except:
            - "x264 (10-bit)"

      - trash_id: 722b624f9af1e492284c4bc842153a38
        name: "[Anime] Planning - 1080p"
        reset_unmatched_scores:
          enabled: true
          except:
            - "x264 (10-bit)"

    custom_formats:
      - trash_ids:
          - cae4ca30163749b891686f95532519bd  # AV1
        assign_scores_to:
          - name: "[Anime] Watching - 1080p"
            score: 0
          - name: "[Anime] Planning - 1080p"
            score: 0
